### ISSUE TITLE
你好啊

### ISSUE THREAD

**Issue by c-jeremy** [Learn-Python-together/Python-files#1]
**你好**
我是小曹162020。
我想说什么来着？呃我哪知道。
总之你可以在这个仓库里面上传你的文件，请不要在未经原作者允许的情况下删除文件，谢谢！

**Comment by Ella1102-Python** [comment]
Hi~ o(*￣▽￣*)ブ

**Comment by Ella1102-Python** [comment]
童鞋你好~

**Comment by c-jeremy** [comment]
> Hi~ o(_￣▽￣_)ブ

你好，我是小曹162020，有什么可以帮到您的吗？

**Comment by c-jeremy** [comment]
（客服腔）

**Comment by Ella1102-Python** [comment]
emmm.....暂时没有~谢谢啦~
【戏精已上线~】
