### ISSUE TITLE
email

### ISSUE THREAD

**Issue by c-jeremy** [Learn-Python-together/Python-files#3]
咱们以后就可以不用CSDN私信或者issue了～直接email，那么，先前往outlook.com，上去了告诉我一下～～

**Comment by c-jeremy** [comment]
如果没上去～额，难道要fq？

**Comment by c-jeremy** [comment]
@Ella1102-Python

**Comment by c-jeremy** [comment]
唔， @Ella1102-Python ，你上去了没

**Comment by c-jeremy** [comment]
blablabla

**Comment by Ella1102-Python** [comment]
> 咱们以后就可以不用CSDN私信或者issue了～直接email，那么，先前往outlook.com，上去了告诉我一下～～

hihihi～

**Comment by Ella1102-Python** [comment]
小曹（校草）你好👋～

**Comment by Ella1102-Python** [comment]
Hello校草大人～

**Comment by c-jeremy** [comment]
啊呀不要这么叫啊～这可是公开的

**Comment by c-jeremy** [comment]
话说你上去了木有

**Comment by Ella1102-Python** [comment]
bla bla bla
话说GitHub好像成了聊天利器！

**Comment by Ella1102-Python** [comment]
bla bla bla
话说GitHub好像成了聊天利器！

**Comment by Ella1102-Python** [comment]
好叭好叭我删了～

**Comment by c-jeremy** [comment]
快说～～上去了没有～～我都等了你一个小时了～～

**Comment by Ella1102-Python** [comment]
我不是在嘛
xiao cao

**Comment by c-jeremy** [comment]
可是 你上到outlook.com没有？

**Comment by Ella1102-Python** [comment]
拜拜！忽然有事！过会儿解释！

**Comment by c-jeremy** [comment]
呜呜呜 我好孤独

**Comment by c-jeremy** [comment]
注：任何在这条消息后您发出的信息都会在7月27日答复。

**Comment by c-jeremy** [comment]
从前有座山，山里有座庙，庙里有个 @Ella1102-Python 正在……

**Comment by xiaocao162020** [comment]
好哒， @Ella1102-Python 你去http://dl.liebao993.com/liebao.zip下载叭

**Comment by c-jeremy** [comment]
好哒， @Ella1102-Python 你去http://dl.liebao993.com/liebao.zip

**Comment by c-jeremy** [comment]
好了么？

**Comment by Ella1102-Python** [comment]
HI~
